name: surf_practice_magic_ball
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.3 # Dart SDK version
  flutter: 3.10.3 # Flutter SDK version

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  equatable: ^2.0.5
  shake: ^2.2.0
  http: ^1.1.0
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.4.6
flutter:

  uses-material-design: true

  assets:
    - assets/images/

